name: nilearn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - joblib
  - scipy
  - statsmodels
  - opencv=3.4.2
  - ipython
  - jupyter
  - jupytext
  - pip
  - plotly
  - python-kaleido
  - dash
  - matplotlib
  - seaborn
  - nilearn
  - nibabel